Syntax 4

SectionVerb {
	EnableSequence [
		cset "name='WSA_CODEC_DMA_RX_0 Audio Mixer MultiMedia1' 1"
		
		cset "name='WSA WSA_AIF_VI Mixer WSA_SPKR_VI_1' 1"
		cset "name='WSA WSA_AIF_VI Mixer WSA_SPKR_VI_2' 1"
		cset "name='WSA2 WSA_AIF_VI Mixer WSA_SPKR_VI_1' 1"
		cset "name='WSA2 WSA_AIF_VI Mixer WSA_SPKR_VI_2' 1"

		cset "name='TweeterLeft COMP Switch' 1"
		cset "name='TweeterRight COMP Switch' 1"
		cset "name='WooferLeft COMP Switch' 1"
		cset "name='WooferRight COMP Switch' 1"

		cset "name='WSA WSA_Softclip0 Enable' 1"
		cset "name='WSA WSA_Softclip1 Enable' 1"
		cset "name='WSA2 WSA_Softclip0 Enable' 1"
		cset "name='WSA2 WSA_Softclip1 Enable' 1"

		cset "name='TweeterLeft VISENSE Switch' 1"
		cset "name='TweeterRight VISENSE Switch' 1"
		cset "name='WooferLeft VISENSE Switch' 1"
		cset "name='WooferRight VISENSE Switch' 1"

		cset "name='TweeterLeft DAC Switch' on"
		cset "name='TweeterRight DAC Switch' on"
		cset "name='WooferLeft DAC Switch' on"
		cset "name='WooferRight DAC Switch' on"

		cset "name='TweeterLeft PA Volume' 12"
		cset "name='TweeterRight PA Volume' 12"
		cset "name='WooferLeft PA Volume' 16"
		cset "name='WooferRight PA Volume' 16"
	]

	DisableSequence [
		cset "name='TweeterLeft PA Volume' 0"
		cset "name='TweeterRight PA Volume' 0"
		cset "name='WooferLeft PA Volume' 0"
		cset "name='WooferRight PA Volume' 0"

		cset "name='TweeterLeft DAC Switch' off"
		cset "name='TweeterRight DAC Switch' off"
		cset "name='WooferLeft DAC Switch' off"
		cset "name='WooferRight DAC Switch' off"
		
		cset "name='WSA_CODEC_DMA_RX_0 Audio Mixer MultiMedia1' 0"
	]
}

SectionDevice."Speaker" {
	Comment "Quad Speaker Array"
	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels "4" 
	}
}
